image: fedora:33

compile:
        tags: 
                - Normal
        script:
                - dnf -y install make gcc libtool which git
                - git clone https://github.com/opensourcerouting/c-capnproto
                - cd c-capnproto
                - git submodule update --init --recursive
                - autoreconf -f -i -s
                - ./configure
                - make install
                - cd ..
                - cp c-capnproto/.libs/libcapnp_c.la src/jtag/drivers/
                - mkdir -p src/jtag/drivers/.libs/
                - cp c-capnproto/.libs/libcapnp_c.so src/jtag/drivers/.libs/
                - ./bootstrap
                - ./configure --enable-tapascojtag
                - make
                - make install
                - openocd --version
        artifacts:
                paths:
                        - src/openocd
                        - src/libopen*
